{% set name = "pyreportjasper" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26b170a7508b660e5a9ba8c1872ffa00c1b2da66e6cae284063666bed0d09b1f

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - jpype1
  run:
    - python >=3.6
    - jpype1

test:
  imports:
    - pyreportjasper
    - test

about:
  home: https://github.com/acesseonline/pyreportjasper
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: This package aims to be a solution to compile and process JasperReports (.jrxml & .jasper files).

extra:
  recipe-maintainers:
    - acesseonline
    - Matt-BF
