{% set name = "pyreportjasper" %}
{% set version = "2.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/acesseonline/pyreportjasper/archive/{{ version }}.tar.gz
  sha256: 6cf62f9f0c8f3a0f16fa7f24446acf0e036e10db5581e85346cca61b888c77a0

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - jpype1
  run:
    - python
    - jpype1

about:
  home: https://pyreportjasper.readthedocs.io
  license: 	GPL-3.0+
  license_family: GPL-3.0+
  license_file: LICENSE.txt
  summary: This package aims to be a solution to compile and process JasperReports (.jrxml & .jasper files).
  doc_url: https://pyreportjasper.readthedocs.io
  dev_url: https://github.com/acesseonline/pyreportjasper 
  
  
extra:
  recipe-maintainers:
    - jadsonbr
