{% set name = "pyreportjasper" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c1597d5d62fc22a1ba3672d44f24fa810e76884dc275e7ce2ca6c7c1f8c87b6d

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pyreportjasper
    - test

about:
  home: https://github.com/PyReportJasper/pyreportjasper
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: This package aims to be a solution to compile and process JasperReports (.jrxml & .jasper files).

extra:
  recipe-maintainers:
    - Matt-BF
